# Generated by Django 4.0.4 on 2022-05-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_alter_score_daoduc_alter_score_dia_alter_score_hoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Daoduc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Dia',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Hoa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Ly',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Sinh',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Su',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='TheDuc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Toan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Van',
            field=models.FloatField(default=0),
        ),
    ]
