# Generated by Django 4.0.4 on 2022-06-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_alter_score_daoduc_alter_score_dia_alter_score_hoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='Students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.classes'),
        ),
        migrations.AlterField(
            model_name='score',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
    ]
