# Generated by Django 4.0.4 on 2022-06-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_classes_students_delete_classlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='Students',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.classes'),
        ),
    ]
