# Generated by Django 4.0.4 on 2022-06-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_rule_alter_score_daoduc_alter_score_dia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='mimnimumScore',
            new_name='minimumScore',
        ),
    ]
