# Generated by Django 4.0.4 on 2022-05-25 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('10A1', '10A1'), ('10A2', '10A2'), ('10A3', '10A3'), ('10A4', '10A4'), ('11A1', '11A1'), ('11A2', '11A2'), ('11A3', '11A3'), ('12A1', '12A1'), ('12A2', '12A2')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nu')], max_length=200, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.student')),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.classes')),
            ],
        ),
    ]
