# Generated by Django 4.0.4 on 2022-05-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Toán', 'Toán'), ('Lý', 'Lý'), ('Hóa', 'Hóa'), ('Sinh', 'Sinh'), ('Sử', 'Sử'), ('Địa', 'Địa'), ('Văn', 'Văn'), ('Đạo đức', 'Đạo đức'), ('Thể dục', 'Thể dục')], max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(choices=[('10A1', '10A1'), ('10A2', '10A2'), ('10A3', '10A3'), ('10A4', '10A4'), ('11A1', '11A1'), ('11A2', '11A2'), ('11A3', '11A3'), ('12A1', '12A1'), ('12A2', '12A2')], max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nũ')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nu')], max_length=200, null=True)),
                ('birthday', models.DateField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.subject')),
            ],
        ),
    ]
