# Generated by Django 4.0.4 on 2022-05-26 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0004_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='Students',
            new_name='students',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('semester', 'students', 'subject')},
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=200, null=True),
        ),
    ]
